sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: LiHaoDong521
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: ${ALIYUN_ACCESS_KEY_ID}
    access-key-secret: ${ALIYUN_ACCESS_KEY_SECRET}
    bucket-name: skyy-takke-outt
  redis:
    host: localhost
    port: 6379
    password: LiHaoDong521
    database: 0
  wechat:
    appid: wx8dd00b36347ee19e
    secret: 0b16c3a7fc2025a291cbdcc3420b4460
  shop:
    address: 陕西省西安市碑林区咸宁西路28号西安交通大学兴庆校区梧桐苑
  baidu:
    ak: VMCR0EZevqXLAeYP09KRAVbHMsJzMm9X